version: "3.8"

services:
  app:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_SSO_URL=${NEXT_PUBLIC_SSO_URL}
        - NEXT_PUBLIC_SSO_PROJECT_ID=${NEXT_PUBLIC_SSO_PROJECT_ID}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
